version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: 'none'
  enable:
    - errcheck
    - gosec
    - misspell
    - unconvert
    - unparam

  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*database/sql.Stmt).Close
        - (*database/sql.Conn).Close
        - (*os.File).Close
        - (os).RemoveAll
        - (os).Remove
        - (os).Setenv
        - (os).Unsetenv
        - (os).Chdir
        - (os).MkdirAll
        - (fmt).Sscanf
        # fmt.Fprintf/Fprintln errors are typically safe to ignore for logging
        - fmt.Fprintf
        - fmt.Fprintln
        - (fmt).Fprintf
        - (fmt).Fprintln
    misspell:
      locale: US

  exclusions:
    rules:
      # G304: File inclusion via variable in tests is safe (test data)
      - path: '_test\.go'
        linters:
          - gosec
        text: "G304"
      # G304: Config/state file loading uses constructed paths, not user input
      # All internal packages read files from constructed paths, not user input
      - path: 'internal/'
        linters:
          - gosec
        text: "G304"
      # G306: File permissions 0644 in tests are acceptable (test fixtures)
      - path: '_test\.go'
        linters:
          - gosec
        text: "G306"
      # G302/G306: Non-sensitive operational files (state, config, logs) can use 0644
      # Internal packages write non-sensitive operational data files
      - path: 'internal/'
        linters:
          - gosec
        text: "G306|G302"
      # G302/G306: Directory/file permissions 0700/0750 are acceptable
      - linters:
          - gosec
        text: "G302.*0700|G301.*0750"
      # G204: Safe subprocess launches with validated arguments (internal tools)
      # All internal packages use subprocess calls for trusted internal tools
      - path: 'internal/'
        linters:
          - gosec
        text: 'G204'
      # G115: Integer overflow conversions are safe in these internal contexts
      # (int->rune for digit chars, int->int32 for proto fields, uintptr->int for syscalls)
      - path: 'internal/'
        linters:
          - gosec
        text: 'G115'
      # G117: Struct fields named AuthToken/APIKey trigger secret-pattern detection
      # but these are type definitions, not hardcoded secrets
      - path: 'internal/'
        linters:
          - gosec
        text: 'G117'
      # G402: TLS InsecureSkipVerify used for internal connectivity checks
      - path: 'internal/'
        linters:
          - gosec
        text: 'G402'
      # G702/G703/G704: Taint analysis for command injection, path traversal, SSRF
      # Internal code uses trusted, constructed inputs (not user-supplied)
      - path: 'internal/'
        linters:
          - gosec
        text: 'G702|G703|G704'
      # errcheck: Ignore unchecked errors in test files for common cleanup patterns
      - path: '_test\.go'
        linters:
          - errcheck
        text: "Error return value of .*(Close|Rollback|RemoveAll|Setenv|Unsetenv|Chdir|MkdirAll|Remove|Write).* is not checked"
      # errcheck: Common cleanup patterns where errors are safe to ignore
      # (Close on net/ws/http connections, process Kill/Wait, JSON Encode to ResponseWriter)
      - linters:
          - errcheck
        text: "Error return value of .*(Close|Kill|Wait|Encode).* is not checked"
      # unparam: Cobra RunE handlers always receive cmd even if unused
      - linters:
          - unparam
        text: "cmd is unused"
      # unparam: Functions matching standard interfaces may have unused params
      - linters:
          - unparam
        text: "is always|is never used|always receives"
      # misspell: "cancelled" is acceptable (British English variant)
      - linters:
          - misspell
        text: "cancelled"

issues:
  uniq-by-line: true
